#ifndef _SDL_xboxshaders_h
#define _SDL_xboxshaders_h

#include "SDL.h"
#include <xtl.h>
#include <d3dx9.h>
#include <XGraphics.h>

void initShaders();
void destroyShaders();
void XBOX_SelectEffect(int effectID);

const static char* g_strShaderNormalSource =
    " float fFilterType : register(c0);            " 
    "                                              "
    " struct PS_IN                                 "
    " {                                            "
    "     float2 TexCoord : TEXCOORD0;             "
    " };                                           "
    "                                              "
    " sampler2D detail : register(s0);             "
    "                                              "
    " float4 main( PS_IN In ) : COLOR0             "
    " {                                            "
    "     float4 color = tex2D( detail, In.TexCoord ); "
    "     return color;                            " 
    " }     ";

/* Scanlines: Simulates CRT scanline effect.                                  *
 * Darkens alternating lines aligned to source pixel rows using sin().        *
 * s0 = game texture, c1 = textureDims                                       *
 * Cost: 1 tex2D + 4 ALU — extremely lightweight.                            */
const static char* g_strShaderScanlinesSource =
    " float2 textureDims : register(c1);                                    \n"
    " sampler2D detail : register(s0);                                      \n"
    " struct PS_IN { float2 TexCoord : TEXCOORD0; };                        \n"
    "                                                                       \n"
    " static const float PI = 3.14159265;                                   \n"
    "                                                                       \n"
    " float4 main(PS_IN In) : COLOR0                                        \n"
    " {                                                                     \n"
    "     float4 color = tex2D(detail, In.TexCoord);                        \n"
    "     float scanline = sin(In.TexCoord.y * textureDims.y * PI);         \n"
    "     float mask = 1.0 - 0.35 * (1.0 - scanline * scanline);           \n"
    "     return float4(color.rgb * mask, color.a);                         \n"
    " }                                                                     \n";

/* CRT: Simulates a curved CRT television.                                    *
 * Barrel distortion + scanlines + vignette.                                  *
 * s0 = game texture, c1 = textureDims                                       *
 * Cost: 1 tex2D + ~15 ALU — lightweight for Xbox 360 Xenos.                 */
const static char* g_strShaderCRTSource =
    " float2 textureDims : register(c1);                                    \n"
    " sampler2D detail : register(s0);                                      \n"
    " struct PS_IN { float2 TexCoord : TEXCOORD0; };                        \n"
    "                                                                       \n"
    " static const float PI = 3.14159265;                                   \n"
    " static const float BARREL_AMOUNT = 0.1;                               \n"
    "                                                                       \n"
    " float4 main(PS_IN In) : COLOR0                                        \n"
    " {                                                                     \n"
    "     /* Barrel distortion */                                           \n"
    "     float2 uv = In.TexCoord * 2.0 - 1.0;                             \n"
    "     float r2 = dot(uv, uv);                                          \n"
    "     uv *= 1.0 + r2 * BARREL_AMOUNT;                                  \n"
    "     uv = uv * 0.5 + 0.5;                                             \n"
    "                                                                       \n"
    "     /* Out-of-bounds check */                                         \n"
    "     float2 inside = step(0.0, uv) * step(uv, 1.0);                   \n"
    "     float mask_bounds = inside.x * inside.y;                          \n"
    "                                                                       \n"
    "     /* Sample texture */                                              \n"
    "     float4 color = tex2D(detail, uv);                                 \n"
    "                                                                       \n"
    "     /* Scanlines */                                                   \n"
    "     float scanline = sin(uv.y * textureDims.y * PI);                  \n"
    "     float mask_scan = 1.0 - 0.35 * (1.0 - scanline * scanline);      \n"
    "                                                                       \n"
    "     /* Vignette */                                                    \n"
    "     float2 vig = uv * (1.0 - uv);                                    \n"
    "     float vignette = saturate(pow(vig.x * vig.y * 15.0, 0.25));      \n"
    "                                                                       \n"
    "     float3 final_color = color.rgb * mask_scan * vignette;            \n"
    "     return float4(final_color * mask_bounds, 1.0);                    \n"
    " }                                                                     \n";

/* HQ2x: Real Maxim Stepin algorithm with LUT - single pass.                 *
 * Original by Maxim Stepin, Cameron Zemek, Jules Blok - LGPL 2.1            *
 * Adapted for Xbox 360 D3D9 pipeline.                                       *
 * s0 = game texture, s1 = LUT texture (256x64), c1 = textureDims            */
const static char* g_strShaderHQ2xSource =
    " float2 textureDims : register(c1);                                    \n"
    " sampler2D detail : register(s0);                                      \n"
    " sampler2D lutTex : register(s1);                                      \n"
    " struct PS_IN { float2 TexCoord : TEXCOORD0; };                        \n"
    "                                                                       \n"
    " static const float3 yuv_threshold = float3(48.0/255.0, 7.0/255.0, 6.0/255.0); \n"
    " static const float3 yuv_offset = float3(0.0, 0.5, 0.5);              \n"
    "                                                                       \n"
    " float3 toYUV(float3 c) {                                              \n"
    "     float3 yuv;                                                       \n"
    "     yuv.x = dot(c, float3( 0.299, 0.587, 0.114));                     \n"
    "     yuv.y = dot(c, float3(-0.169,-0.331, 0.5  ));                     \n"
    "     yuv.z = dot(c, float3( 0.5,  -0.419,-0.081));                     \n"
    "     return yuv;                                                       \n"
    " }                                                                     \n"
    "                                                                       \n"
    " float isDiff(float3 a, float3 b) {                                    \n"
    "     float3 d = abs((a + yuv_offset) - (b + yuv_offset));              \n"
    "     float3 cmp = step(yuv_threshold + 0.0001, d);                     \n"
    "     return saturate(cmp.x + cmp.y + cmp.z);                           \n"
    " }                                                                     \n"
    "                                                                       \n"
    " float4 main(PS_IN In) : COLOR0                                        \n"
    " {                                                                     \n"
    "     float2 texel = 1.0 / textureDims;                                 \n"
    "     float2 uv = In.TexCoord;                                          \n"
    "     float dx = texel.x;                                               \n"
    "     float dy = texel.y;                                               \n"
    "                                                                       \n"
    "     float2 fp = frac(uv * textureDims);                               \n"
    "     float2 quad = sign(-0.5 + fp);                                    \n"
    "                                                                       \n"
    "     float3 p1 = tex2D(detail, uv).rgb;                                \n"
    "     float3 p2 = tex2D(detail, uv + float2(dx,dy) * quad).rgb;        \n"
    "     float3 p3 = tex2D(detail, uv + float2(dx, 0) * quad).rgb;        \n"
    "     float3 p4 = tex2D(detail, uv + float2( 0,dy) * quad).rgb;        \n"
    "                                                                       \n"
    "     float3 w1 = toYUV(tex2D(detail, uv+float2(-dx,-dy)).rgb);        \n"
    "     float3 w2 = toYUV(tex2D(detail, uv+float2(  0,-dy)).rgb);        \n"
    "     float3 w3 = toYUV(tex2D(detail, uv+float2( dx,-dy)).rgb);        \n"
    "     float3 w4 = toYUV(tex2D(detail, uv+float2(-dx,  0)).rgb);        \n"
    "     float3 w5 = toYUV(p1);                                            \n"
    "     float3 w6 = toYUV(tex2D(detail, uv+float2( dx,  0)).rgb);        \n"
    "     float3 w7 = toYUV(tex2D(detail, uv+float2(-dx, dy)).rgb);        \n"
    "     float3 w8 = toYUV(tex2D(detail, uv+float2(  0, dy)).rgb);        \n"
    "     float3 w9 = toYUV(tex2D(detail, uv+float2( dx, dy)).rgb);        \n"
    "                                                                       \n"
    "     float pattern = isDiff(w5,w1)*1.0   + isDiff(w5,w2)*2.0           \n"
    "                   + isDiff(w5,w3)*4.0   + isDiff(w5,w4)*8.0           \n"
    "                   + isDiff(w5,w6)*16.0  + isDiff(w5,w7)*32.0          \n"
    "                   + isDiff(w5,w8)*64.0  + isDiff(w5,w9)*128.0;        \n"
    "                                                                       \n"
    "     float cross_val = isDiff(w4,w2)*1.0 + isDiff(w2,w6)*2.0           \n"
    "                     + isDiff(w8,w4)*4.0 + isDiff(w6,w8)*8.0;          \n"
    "                                                                       \n"
    "     float2 index;                                                     \n"
    "     index.x = pattern;                                                \n"
    "     index.y = cross_val * 4.0                                         \n"
    "             + floor(fp.x * 2.0) + floor(fp.y * 2.0) * 2.0;           \n"
    "                                                                       \n"
    "     float2 lutStep = float2(1.0/256.0, 1.0/64.0);                    \n"
    "     float2 lutOff  = lutStep * 0.5;                                   \n"
    "     float4 weights = tex2D(lutTex, index * lutStep + lutOff);         \n"
    "     float wsum = dot(weights, float4(1,1,1,1));                       \n"
    "     float4 nw = weights / max(wsum, 0.001);                           \n"
    "     float3 res = p1*nw.x + p2*nw.y + p3*nw.z + p4*nw.w;             \n"
    "                                                                       \n"
    "     return float4(res, 1.0);                                          \n"
    " }                                                                     \n";

/* HQ3x: Real Maxim Stepin algorithm with LUT - single pass.                 *
 * Same as HQ2x but SCALE=3, LUT is 256x144.                                 *
 * s0 = game texture, s1 = LUT texture (256x144), c1 = textureDims           */
const static char* g_strShaderHQ3xSource =
    " float2 textureDims : register(c1);                                    \n"
    " sampler2D detail : register(s0);                                      \n"
    " sampler2D lutTex : register(s1);                                      \n"
    " struct PS_IN { float2 TexCoord : TEXCOORD0; };                        \n"
    "                                                                       \n"
    " static const float3 yuv_threshold = float3(48.0/255.0, 7.0/255.0, 6.0/255.0); \n"
    " static const float3 yuv_offset = float3(0.0, 0.5, 0.5);              \n"
    "                                                                       \n"
    " float3 toYUV(float3 c) {                                              \n"
    "     float3 yuv;                                                       \n"
    "     yuv.x = dot(c, float3( 0.299, 0.587, 0.114));                     \n"
    "     yuv.y = dot(c, float3(-0.169,-0.331, 0.5  ));                     \n"
    "     yuv.z = dot(c, float3( 0.5,  -0.419,-0.081));                     \n"
    "     return yuv;                                                       \n"
    " }                                                                     \n"
    "                                                                       \n"
    " float isDiff(float3 a, float3 b) {                                    \n"
    "     float3 d = abs((a + yuv_offset) - (b + yuv_offset));              \n"
    "     float3 cmp = step(yuv_threshold + 0.0001, d);                     \n"
    "     return saturate(cmp.x + cmp.y + cmp.z);                           \n"
    " }                                                                     \n"
    "                                                                       \n"
    " float4 main(PS_IN In) : COLOR0                                        \n"
    " {                                                                     \n"
    "     float2 texel = 1.0 / textureDims;                                 \n"
    "     float2 uv = In.TexCoord;                                          \n"
    "     float dx = texel.x;                                               \n"
    "     float dy = texel.y;                                               \n"
    "                                                                       \n"
    "     float2 fp = frac(uv * textureDims);                               \n"
    "     float2 quad = sign(-0.5 + fp);                                    \n"
    "                                                                       \n"
    "     float3 p1 = tex2D(detail, uv).rgb;                                \n"
    "     float3 p2 = tex2D(detail, uv + float2(dx,dy) * quad).rgb;        \n"
    "     float3 p3 = tex2D(detail, uv + float2(dx, 0) * quad).rgb;        \n"
    "     float3 p4 = tex2D(detail, uv + float2( 0,dy) * quad).rgb;        \n"
    "                                                                       \n"
    "     float3 w1 = toYUV(tex2D(detail, uv+float2(-dx,-dy)).rgb);        \n"
    "     float3 w2 = toYUV(tex2D(detail, uv+float2(  0,-dy)).rgb);        \n"
    "     float3 w3 = toYUV(tex2D(detail, uv+float2( dx,-dy)).rgb);        \n"
    "     float3 w4 = toYUV(tex2D(detail, uv+float2(-dx,  0)).rgb);        \n"
    "     float3 w5 = toYUV(p1);                                            \n"
    "     float3 w6 = toYUV(tex2D(detail, uv+float2( dx,  0)).rgb);        \n"
    "     float3 w7 = toYUV(tex2D(detail, uv+float2(-dx, dy)).rgb);        \n"
    "     float3 w8 = toYUV(tex2D(detail, uv+float2(  0, dy)).rgb);        \n"
    "     float3 w9 = toYUV(tex2D(detail, uv+float2( dx, dy)).rgb);        \n"
    "                                                                       \n"
    "     float pattern = isDiff(w5,w1)*1.0   + isDiff(w5,w2)*2.0           \n"
    "                   + isDiff(w5,w3)*4.0   + isDiff(w5,w4)*8.0           \n"
    "                   + isDiff(w5,w6)*16.0  + isDiff(w5,w7)*32.0          \n"
    "                   + isDiff(w5,w8)*64.0  + isDiff(w5,w9)*128.0;        \n"
    "                                                                       \n"
    "     float cross_val = isDiff(w4,w2)*1.0 + isDiff(w2,w6)*2.0           \n"
    "                     + isDiff(w8,w4)*4.0 + isDiff(w6,w8)*8.0;          \n"
    "                                                                       \n"
    "     float2 index;                                                     \n"
    "     index.x = pattern;                                                \n"
    "     index.y = cross_val * 9.0                                         \n"
    "             + floor(fp.x * 3.0) + floor(fp.y * 3.0) * 3.0;           \n"
    "                                                                       \n"
    "     float2 lutStep = float2(1.0/256.0, 1.0/144.0);                   \n"
    "     float2 lutOff  = lutStep * 0.5;                                   \n"
    "     float4 weights = tex2D(lutTex, index * lutStep + lutOff);         \n"
    "     float wsum = dot(weights, float4(1,1,1,1));                       \n"
    "     float4 nw = weights / max(wsum, 0.001);                           \n"
    "     float3 res = p1*nw.x + p2*nw.y + p3*nw.z + p4*nw.w;             \n"
    "                                                                       \n"
    "     return float4(res, 1.0);                                          \n"
    " }                                                                     \n";

/* HQ4x: Real Maxim Stepin algorithm with LUT - single pass.                 *
 * Same as HQ2x/HQ3x but SCALE=4, LUT is 256x256.                           *
 * s0 = game texture, s1 = LUT texture (256x256), c1 = textureDims           */
const static char* g_strShaderHQ4xSource =
    " float2 textureDims : register(c1);                                    \n"
    " sampler2D detail : register(s0);                                      \n"
    " sampler2D lutTex : register(s1);                                      \n"
    " struct PS_IN { float2 TexCoord : TEXCOORD0; };                        \n"
    "                                                                       \n"
    " static const float3 yuv_threshold = float3(48.0/255.0, 7.0/255.0, 6.0/255.0); \n"
    " static const float3 yuv_offset = float3(0.0, 0.5, 0.5);              \n"
    "                                                                       \n"
    " float3 toYUV(float3 c) {                                              \n"
    "     float3 yuv;                                                       \n"
    "     yuv.x = dot(c, float3( 0.299, 0.587, 0.114));                     \n"
    "     yuv.y = dot(c, float3(-0.169,-0.331, 0.5  ));                     \n"
    "     yuv.z = dot(c, float3( 0.5,  -0.419,-0.081));                     \n"
    "     return yuv;                                                       \n"
    " }                                                                     \n"
    "                                                                       \n"
    " float isDiff(float3 a, float3 b) {                                    \n"
    "     float3 d = abs((a + yuv_offset) - (b + yuv_offset));              \n"
    "     float3 cmp = step(yuv_threshold + 0.0001, d);                     \n"
    "     return saturate(cmp.x + cmp.y + cmp.z);                           \n"
    " }                                                                     \n"
    "                                                                       \n"
    " float4 main(PS_IN In) : COLOR0                                        \n"
    " {                                                                     \n"
    "     float2 texel = 1.0 / textureDims;                                 \n"
    "     float2 uv = In.TexCoord;                                          \n"
    "     float dx = texel.x;                                               \n"
    "     float dy = texel.y;                                               \n"
    "                                                                       \n"
    "     float2 fp = frac(uv * textureDims);                               \n"
    "     float2 quad = sign(-0.5 + fp);                                    \n"
    "                                                                       \n"
    "     float3 p1 = tex2D(detail, uv).rgb;                                \n"
    "     float3 p2 = tex2D(detail, uv + float2(dx,dy) * quad).rgb;        \n"
    "     float3 p3 = tex2D(detail, uv + float2(dx, 0) * quad).rgb;        \n"
    "     float3 p4 = tex2D(detail, uv + float2( 0,dy) * quad).rgb;        \n"
    "                                                                       \n"
    "     float3 w1 = toYUV(tex2D(detail, uv+float2(-dx,-dy)).rgb);        \n"
    "     float3 w2 = toYUV(tex2D(detail, uv+float2(  0,-dy)).rgb);        \n"
    "     float3 w3 = toYUV(tex2D(detail, uv+float2( dx,-dy)).rgb);        \n"
    "     float3 w4 = toYUV(tex2D(detail, uv+float2(-dx,  0)).rgb);        \n"
    "     float3 w5 = toYUV(p1);                                            \n"
    "     float3 w6 = toYUV(tex2D(detail, uv+float2( dx,  0)).rgb);        \n"
    "     float3 w7 = toYUV(tex2D(detail, uv+float2(-dx, dy)).rgb);        \n"
    "     float3 w8 = toYUV(tex2D(detail, uv+float2(  0, dy)).rgb);        \n"
    "     float3 w9 = toYUV(tex2D(detail, uv+float2( dx, dy)).rgb);        \n"
    "                                                                       \n"
    "     float pattern = isDiff(w5,w1)*1.0   + isDiff(w5,w2)*2.0           \n"
    "                   + isDiff(w5,w3)*4.0   + isDiff(w5,w4)*8.0           \n"
    "                   + isDiff(w5,w6)*16.0  + isDiff(w5,w7)*32.0          \n"
    "                   + isDiff(w5,w8)*64.0  + isDiff(w5,w9)*128.0;        \n"
    "                                                                       \n"
    "     float cross_val = isDiff(w4,w2)*1.0 + isDiff(w2,w6)*2.0           \n"
    "                     + isDiff(w8,w4)*4.0 + isDiff(w6,w8)*8.0;          \n"
    "                                                                       \n"
    "     float2 index;                                                     \n"
    "     index.x = pattern;                                                \n"
    "     index.y = cross_val * 16.0                                        \n"
    "             + floor(fp.x * 4.0) + floor(fp.y * 4.0) * 4.0;           \n"
    "                                                                       \n"
    "     float2 lutStep = float2(1.0/256.0, 1.0/256.0);                   \n"
    "     float2 lutOff  = lutStep * 0.5;                                   \n"
    "     float4 weights = tex2D(lutTex, index * lutStep + lutOff);         \n"
    "     float wsum = dot(weights, float4(1,1,1,1));                       \n"
    "     float4 nw = weights / max(wsum, 0.001);                           \n"
    "     float3 res = p1*nw.x + p2*nw.y + p3*nw.z + p4*nw.w;             \n"
    "                                                                       \n"
    "     return float4(res, 1.0);                                          \n"
    " }                                                                     \n";

const static char* g_strShaderFullscreen =
"float4 vParams : register(c0);											\n"
"float4 vRes    : register(c1);                                         \n"
"                                                                       \n"
"struct VS_IN {                                                         \n"
"    float4 Pos : POSITION;                                             \n"
"    float2 UV  : TEXCOORD0;                                            \n"
"};                                                                     \n"
"                                                                       \n"
"struct VS_OUT {                                                        \n"
"    float4 Pos : POSITION0;                                            \n"
"    float2 UV  : TEXCOORD0;                                            \n"
"};                                                                     \n"
"                                                                       \n"
"VS_OUT main(VS_IN In) {                                                \n"
"    VS_OUT Out;                                                        \n"
"    float2 screenRes = vRes.xy;                                        \n"
"    float2 imgRes    = vRes.zw;                                        \n"
"    float ratio      = vParams.x;                                      \n"
"    float forceFS    = vParams.y;                                      \n"
"                                                                       \n"
"    float2 scale;                                                      \n"
"    if (forceFS > 0.5) {                                               \n"
"        float screenRatio = screenRes.x / screenRes.y;                 \n"
"        if (ratio > screenRatio)                                       \n"
"            scale = float2(1.0, screenRatio / ratio);                  \n"
"        else                                                           \n"
"            scale = float2(ratio / screenRatio, 1.0);                  \n"
"    } else {                                                           \n"
"        scale = (imgRes / screenRes) * float2(ratio, 1.0);             \n"
"    }                                                                  \n"
"                                                                       \n"
"    Out.Pos.x = In.Pos.x * scale.x;                                    \n"
"    Out.Pos.y = In.Pos.y * scale.y;                                    \n"
"    Out.Pos.z = 0.0f;                                                  \n"
"    Out.Pos.w = 1.0f;                                                  \n"
"                                                                       \n"
"    Out.UV = In.UV;                                                    \n"
"    return Out;                                                        \n"
"}																		\n";	

#endif